# inventory/lab/hosts.yml

all:
  children:

    proxmox_ssh:
      hosts:
        devproxn2:
          ansible_host: 10.25.4.21
          ansible_user: ansible

    proxmox_api:
      hosts:
        devproxn2:
          ansible_host: 10.25.4.21

        devproxn3:
          ansible_host: 10.25.4.22

        devproxn4:
          ansible_host: 10.25.4.23