# Requires BWS_ACCESS_TOKEN environment variable
# Example:
# source ./bws.env
# before running ansible-playbook
bws_access_token: "{{ lookup('ansible.builtin.env', 'bws_access_token') }}"

proxmox_api_host: devproxn2.ph-cov.local
proxmox_api_user: "{{ lookup('bitwarden.secrets.lookup', '9a6d8b32-7528-413b-a046-b4db010859a9', access_token=bws_access_token) }}"
proxmox_api_token_id: "{{ lookup('bitwarden.secrets.lookup', 'fc074f09-edcf-43d4-9ffa-b4db01089e8f', access_token=bws_access_token) }}"
proxmox_api_token_secret: "{{ lookup('bitwarden.secrets.lookup', '8571f211-1376-4b30-8999-b4db0108b59c', access_token=bws_access_token) }}"
proxmox_node: devproxn2

template_vmid: 9000
template_name: ubuntu-2404-template

vmid: 9005
vm_name: PNMON002
vm_description: "This is the Zabbix monitoring VM"
vm_cores: 4
vm_memory: 4024
vm_ip: 10.25.4.200/24
vm_gateway: 10.25.4.1
vm_dns: 10.25.4.11
storage_ip: 10.25.7.50/24
vm_searchdomain: ph-cov.local
disk_resize: +35G

inventory_group: zabbix

# # Zabbix .env file
# Generate .env file
# #postgres sql
# POSTGRES_DB=zabbix
# POSTGRES_USER=zabbix
# POSTGRES_PASSWORD=change-me
# #smtp auth
# SMTP_USERNAME=
# SMTP_PASSWORD=
# # SMTP
# SMTP_HOST=
# SMTP_PORT=
# # SNMPv3
# SNMPV3_AUTH_PASSPHRASE=
# SNMPV3_PRIV_PASSPHRASE=
# #nfs
# POSTGRES_NFS_OPTS=addr=10.25.7.4,nfsvers=4,rw,hard,timeo=600,retrans=2
# POSTGRES_NFS_PATH=:/mnt/devprox_nvme/monitor_zabbix/dev