---
- name: Deploy Zabbix VM
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../vars/deploy-zabbix-vars.yml

  module_defaults:
    group/community.proxmox.proxmox:
      api_host: "{{ proxmox_api_host }}"
      api_user: "{{ proxmox_api_user }}"
      api_token_id: "{{ proxmox_api_token_id }}"
      api_token_secret: "{{ proxmox_api_token_secret }}"

  roles:
    - proxmox_vm
    - ubuntu_security

- name: Configure Zabbix VM
  hosts: zabbix
  gather_facts: false

  vars_files:
    - ../vars/deploy-zabbix-vars.yml

  tasks:
  
    - name: Verify connectivity
      ansible.builtin.ping:
  
    - name: Create application directory
      become: true
      ansible.builtin.file:
        path: "{{ app_path }}"
        state: directory
        owner: ansible
        group: ansible
        mode: "0755"
    
    - name: Create SSH directory
      become: true
      ansible.builtin.file:
        path: /home/ansible/.ssh
        state: directory
        owner: ansible
        group: ansible
        mode: "0700"

    - name: Deploy GitHub private key
      become: true
      no_log: true
      ansible.builtin.copy:
        content: "{{ github_deploy_key }}"
        dest: /home/ansible/.ssh/id_ed25519
        owner: ansible
        group: ansible
        mode: "0600"

    - name: Create SSH config
      ansible.builtin.copy:
        dest: /home/ansible/.ssh/config
        owner: ansible
        group: ansible
        mode: "0600"
        content: |
          Host github.com
              HostName ssh.github.com
              User git
              Port 443
              IdentityFile ~/.ssh/id_ed25519
      
    - name: Clone repository
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "{{ app_path }}"
        version: main
        key_file: "/home/ansible/.ssh/id_ed25519"
        accept_hostkey: true
        force: true

    - name: Create .env file
      ansible.builtin.template:
        src: "{{ env_template }}"
        dest: /opt/zabbix-pharmaron/.env
        owner: ansible
        group: ansible
        mode: "0600"
      
    - name: Start containers
      become: true
      community.docker.docker_compose_v2:
        project_src: "{{ app_path }}"
        state: present